version: '3'

services:
  node:
    image: node:latest
    volumes:
      - "./user_api:/var/www"  
    ports:
      - "8081:3000"
    links:
      - mongo
    command: bash -c "cd /var/www && ./node_modules/.bin/pm2 start startup.json --name API --no-daemon"
    environment:
      - URL_MONGO=mongodb://user_api:docker1234@mongo
      - ACCESS_TOKEN_SECRET=4242XX424208
      - REFRESH_TOKEN_SECRET=424200000X1

  mongo:
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=user_api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234

  api-service:
      build: ./image_api/
      volumes: 
          - ./image_api/:/app
      ports: 
          - 5000:5000
      expose:
          - '5000'
      environment: 
          PORT: 5000
          FLASK_DEBUG: 1